/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'kwon37xi' at '15. 12. 1 오전 12:14' with Gradle 2.9
 *
 * @author kwon37xi, @date 15. 12. 1 오전 12:14
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
